@echo off
setlocal enabledelayedexpansion

set CONF_FILE=src-tauri\tauri.conf.json
set PYPROJECT_FILE=pyproject.toml

:: 1. 确保工作区干净
git diff-index --quiet HEAD --
if %errorlevel% neq 0 (
    echo ❌ 工作区有未提交的变更，请先提交或暂存后再运行。
    git status --short
    exit /b 1
)

:: 2. 读取当前版本
for /f "tokens=2 delims=:," %%a in ('findstr /r /c:"\"version\"" %CONF_FILE%') do (
    set "raw=%%a"
    set "raw=!raw:"=!"
    set "raw=!raw: =!"
    set "current=!raw!"
)
if "%current%"=="" (
    echo ❌ 无法从 %CONF_FILE% 中读取版本号
    exit /b 1
)
echo 当前版本: %current%

:: 3. 解析并递增 patch 版本号
for /f "tokens=1,2,3 delims=." %%a in ("%current%") do (
    set major=%%a
    set minor=%%b
    set patch=%%c
)
set /a new_patch=%patch% + 1
set new_version=%major%.%minor%.%new_patch%
echo 新版本:   %new_version%

:: 4. 更新 tauri.conf.json 中的版本号
powershell -Command "(Get-Content '%CONF_FILE%') -replace '\"version\": \"%current%\"', '\"version\": \"%new_version%\"' | Set-Content '%CONF_FILE%'"
echo ✅ 已更新 %CONF_FILE%

:: 4.1 同步更新 pyproject.toml 中的版本号（build.py 从此读取版本生成 latest.json）
powershell -Command "(Get-Content '%PYPROJECT_FILE%') -replace '^version = \"%current%\"', 'version = \"%new_version%\"' | Set-Content '%PYPROJECT_FILE%'"
echo ✅ 已更新 %PYPROJECT_FILE%

:: 4.2 同步 uv.lock 中的项目版本号
uv lock
if %errorlevel% neq 0 (
    echo ❌ uv lock 失败，请检查 uv 是否可用
    exit /b 1
)
echo ✅ 已同步 uv.lock

:: 5. 暂存版本变更文件
git add %CONF_FILE%
git add %PYPROJECT_FILE%
git add uv.lock
git add src-tauri\Cargo.toml >nul 2>&1
git add src-tauri\permissions\autogenerated\ >nul 2>&1

:: 6. 提交
git commit -m "chore: bump version to %new_version%"
echo ✅ 已提交

:: 7. 打标签
git tag v%new_version%
echo ✅ 已创建标签 v%new_version%

:: 8. 推送
git push origin master
git push origin v%new_version%
echo ✅ 已推送，GitHub Release 将自动触发。
echo 🔗 https://github.com/xuechongfei/llm-apig/actions

endlocal