#!/bin/bash
# release.sh — 自动递增版本号、提交、打标签、推送，触发 GitHub Release
set -euo pipefail

CONF_FILE="src-tauri/tauri.conf.json"

# 1. 确保工作区干净
if ! git diff-index --quiet HEAD --; then
  echo "❌ 工作区有未提交的变更，请先提交或暂存后再运行。"
  git status --short
  exit 1
fi

# 2. 读取当前版本
current=$(grep '"version"' "$CONF_FILE" | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')
if [[ -z "$current" ]]; then
  echo "❌ 无法从 $CONF_FILE 中读取版本号"
  exit 1
fi
echo "当前版本: $current"

# 3. 解析并递增 patch 版本号
IFS='.' read -r major minor patch <<< "$current"
new_patch=$((patch + 1))
new_version="${major}.${minor}.${new_patch}"
echo "新版本:   $new_version"

# 4. 更新 tauri.conf.json 中的版本号
sed -i "s/\"version\": \"$current\"/\"version\": \"$new_version\"/" "$CONF_FILE"
echo "✅ 已更新 $CONF_FILE"

# 5. 暂存版本变更文件
git add "$CONF_FILE"

# 如果 Cargo.toml 或权限文件有变更也一并暂存
git add src-tauri/Cargo.toml 2>/dev/null || true
git add src-tauri/permissions/autogenerated/ 2>/dev/null || true

# 6. 提交
git commit -m "chore: bump version to $new_version" \
  -m "Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
echo "✅ 已提交"

# 7. 打标签
git tag "v${new_version}"
echo "✅ 已创建标签 v${new_version}"

# 8. 推送
git push origin master
git push origin "v${new_version}"
echo "✅ 已推送，GitHub Release 将自动触发。"
echo "🔗 https://github.com/xuechongfei/llm-apig/actions"